language: cpp
os: linux
dist: focal
compiler:
  - gcc

sudo: true

git:
  submodules: false
before_install:
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . --target all
  - ctest --output-on-failure
  
