language: cpp
os: linux
dist: focal
compiler:
  - gcc

sudo: true

git:
  submodules: false
before_install:
  - git submodule update --init --recursive
addons:
  apt:
    packages:
    - binutils-gold
    - libglew-dev
    - mesa-common-dev
    - libglew1.5-dev
    - libglm-dev
    - mesa-utils
    - freeglut3-dev
    update: true

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . --target all
  - ctest --output-on-failure
